### ISSUE TITLE
[FEAT] Publish arm64 images

### ISSUE THREAD

**Issue by speshak** [leplusorg/docker-xml#56]
I would like arm64 images for this project as well, mainly for use on Apple Silicon hardware.

I was able to build working arm64 images [using docker buildx](https://github.com/speshak/docker-xml/pull/1/commits/92475c758887d25011cfa0bd9ab82558a0586f6c) and would be happy to prepare a PR if my approach is acceptable to this project.

**Comment by thomasleplus** [comment]
Hi @speshak, I was already working on it so it's done. Let me know if it works for you and feel free to suggest improvements to what I've done (commit 3a816c929a40d1168b50d9277c3cac74095c9c64).

**Comment by speshak** [comment]
@thomasleplus that change works great for me, thanks for predicting my request. 😄
